### PR TITLE
added navbar and ts support

### PR DESCRIPTION
**Pull request by hoonsubin**
added internal page linking behavior

### CODE REVIEW

**Comment by taskooh** [comment]
@hoonsubin I rebased from the current master. please pull this.

**Comment by taskooh** [comment]
@hoonsubin Can I merge to master after the link works?
Because users cannot link to other pages now. Are you working on it now?

**Comment by hoonsubin** [comment]
@taskooh I'm not working on it yet. Yes please merge it after when the links are working. I'll work on it soon

**Comment by taskooh** [comment]
@Thanks! Other than that, it looks good.
When you are working with internal links, please use "navigate" function in gatsby
https://www.gatsbyjs.org/docs/gatsby-link/

**Comment by hoonsubin** [comment]
@taskooh can you check if this is correct? https://github.com/staketechnologies/HP-2020/pull/3/commits/0e50374c4d1cd484fd708609407588afc1d20b5b

**Comment by taskooh** [comment]
@hoonsubin could you use "navigate" function in gatsby
https://www.gatsbyjs.org/docs/gatsby-link/
instead of react-router?
And sorry that I’m out and cannot run the code!

**Comment by taskooh** [comment]
@hoonsubin Sorry, you are already using!

**Pull request merged**
